pywww/main/urls.py
from django.urls import path
from main.views import hello_world, contacts, contacts2, add_post_form, contact

app_name = 'main'
urlpatterns = [
    path('', hello_world, name='hello_world'),
    path('contacts', contacts, name='contacts'),
    path('contacts2', contacts2, name='contacts2'),
    path('contact', contact, name="contact")
]

pywww/posts/urls.py
from django.urls import path
from posts.views import posts_list, posts_details, add_post_form, toggle_sponsored

app_name = 'posts'

urlpatterns = [
   path('', posts_list, name='list'),
   path('<int:id>', posts_details, name='details'),
   path('add', add_post_form, name='add'),
   path('toggle_sponsored/<int:id>', toggle_sponsored, name='toggle_sponsored'),
]

pywww/pywww/urls.py
# from django.contrib import admin
# from django.urls import path, include
#
# urlpatterns = [
#     path('', include('main.urls')),
#     path('admin/', admin.site.urls),
# ]
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('main.urls')),
                  path('posts/', include('posts.urls')),
                  path('admin/', admin.site.urls),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pywww/main/models.py
from django.db import models

# Create your models here.

class UserProfile(models.Model):
   user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
   bio = models.TextField()

   def __str__(self):
      return f'Profile for {self.user} : {self.bio[:30]}...'

pywww/posts/models.py
from django.db import models
from django.utils.timezone import now, timedelta


class CheckAgeMixin:
    def is_older_than_n_days(self, n=1):
        """Check if created is older than now() - n days"""
        delta = timedelta(days=n)
        return now() - self.created > delta


class Timestamped(models.Model, CheckAgeMixin):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Create your models here.
class Post(Timestamped):
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
        related_name="posts"
    )
    title = models.CharField(max_length=255)  # pole tekstowe o określonej długości
    content = models.TextField()  # pole tekstowe o nieokreślonej długości
    published = models.BooleanField(default=False)  # flaga true/false
    sponsored = models.BooleanField(default=False)  # flaga true/false
    created = models.DateTimeField(auto_now_add=True)  # data utworzenia - tylko przy utworzeniu
    modified = models.DateTimeField(auto_now=True)  # data modyfikacji - zawsze gdy klikniemy save
    tags = models.ManyToManyField('tags.Tag', related_name="posts", blank=True)
    example_file = models.FileField(upload_to='posts/examples/', blank=True, null=True)
    image = models.ImageField(upload_to='posts/images/', blank=True, null=True)

    #
    def is_content_long(self, n_chars=200):
        # napisać metode modelu odpowiadającą na pytanie czy post jest długi.
        # długie posty w szablonie szczgółów skracamy do 200 znaków i dodajemy ...
        return len(self.content) > n_chars

    def short_content(self, n=200):
        return self.content[:n]

    def __str__(self):
        return f'{self.title} by {self.author}'

pywww/tags/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.
class Tag(models.Model):
    name = models.CharField(unique=True, max_length=100)
    slug = models.SlugField(unique=True, max_length=100)

    def save(self, *args, **kwargs):
        if not self.slug:
            n = self.name
            s = slugify(n)
            print(f'Autogeneracja sluga: {n} -> {s}')
            self.slug = s
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

pywww/main/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, HTML, ButtonHolder
from django import forms


class ContactForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    send_to_me = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = 'contact'
        # self.helper.add_input(Submit('submit', 'Wyślij1'))

        self.helper.layout = Layout(
            Fieldset('Dane kontaktowe', 'email'),
            Fieldset('Zawartość', 'title', 'content'),
            Fieldset('Dodatkowe',HTML("Zaznacz jeśli chcesz by wysłać kopię wiadomości do Ciebie"),'send_to_me',),
            ButtonHolder(Submit('submit', 'Wyślij', css_class='btn btn-primary'),css_class="d-flex justify-content-end")
        )

pywww/main/views.py
from pprint import pprint
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest

from main.forms import ContactForm


def hello_world(request: HttpRequest):
    context = {}
    return render(request, 'main/hello.html', context)


def contacts(request: HttpRequest):
    context = {}
    return render(request, 'main/contacts.html', context)


def contact(request: HttpRequest):
    if request.method == 'POST':
        # odbiór danych
        dane_f_formularza = request.POST
        f = ContactForm(request.POST)
        if f.is_valid():
            print('Wyczyszczone dane: ', f.cleaned_data)
        else:
            print('Błędne dane z formularza: ', f.errors)
        return redirect('main:hello_world')
    else:
        context = {'form': ContactForm}
        return render(request, 'main/contact.html', context)

pywww/posts/views.py
from pprint import pprint

from django.contrib.auth.models import User

from posts.models import Post
from django.shortcuts import render, redirect

from tags.models import Tag


def posts_list(request):
    q = title__contains = request.GET.get('q')
    lista_postow = Post.objects.all()
    if q:
        lista_postow = lista_postow.filter(title__contains=q)
    lista_postow = lista_postow.order_by('-sponsored')
    context = {
        'posts_list': lista_postow,
    }
    return render(request, 'posts/list.html', context)


def posts_details(request, id):
    post = Post.objects.get(id=id)
    context = {'post': post}
    return render(request, 'posts/details.html', context)


def toggle_sponsored(request, id):
    post = Post.objects.get(id=id)
    post.sponsored = not post.sponsored
    post.save()
    return redirect('posts:list')


def add_post_form(request):
    if request.method == "POST":
        pprint(dict(request.POST))
        data = {
            "title": request.POST['title'],
            "content": request.POST['content'],
            "published": 'published' in request.POST,
            "author": User.objects.get(id=request.POST['author'])
        }
        post = Post.objects.create(**data)
        for tag_id in request.POST.getlist('tags'):
            tag_id = int(tag_id)
            t = Tag.objects.get(id=tag_id)
            post.tags.add(t)
        return redirect('posts:list')
    else:
        # wczytać tagi
        # dodać do kontekstu
        context = {
            'tags': Tag.objects.all(),
            'authors': User.objects.all(),
        }
        return render(request, 'posts/add.html', context)

pywww/pywww/views.py
from django.http import HttpResponse
from posts.models import Post

def posts_list(request):
    return HttpResponse('sfsdfs')

pywww/tags/views.py
from django.shortcuts import render

# Create your views here.

pywww/main/templates/main/base.html
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>
        {% block title %}{% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-sm bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static "main/img/logo1.png" %}" width="25" height="30">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'main:hello_world' %}">Główna</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:contacts' %}">Kontakty</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:list' %}">Lista postów</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:add' %}">Dodaj post</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col">&nbsp;
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            &nbsp;
        </div>
    <div class="row">
        <div class="col">
            &nbsp;
        </div>
    </div>
</div>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">&copy; 2021 Pywww, Inc</p>

    <a href="/"
       class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <img src="{% static "main/img/logo1.png" %}" alt="logo" width="30px">
    </a>
    <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="{% url 'main:contacts' %}" class="nav-link px-2 text-muted">Contacts</a></li>
    </ul>
</footer>


{#<script>#}
{#    $(function () {#}
{#        $('[data-toggle="tooltip"]').tooltip()#}
{#    })#}
{#</script>#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>
</body>
</html>

pywww/main/templates/main/contact.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Kontakt{% endblock %}
{% block content %}
       {% crispy form form.helper %}
{% comment %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Send</button>
</form>
{% endcomment %}
{% endblock %}

pywww/main/templates/main/contacts.html
{% extends "main/base.html" %}
{% block title %}Lista postów{% endblock %}
{% block content %}
<h1>Nagłówek listy</h1>
{% endblock %}

pywww/main/templates/main/contacts2.html
{% extends "main/base.html" %}
{% block title %}Lista postów{% endblock %}
{% block content %}
<h1>Nagłówek listy</h1>
<div class="container overflow-hidden text-center">
    <div class="row gy-5">
        <div class="col-6">
            <div class="p-3 border bg-light"><a href="http://www.google.com" class="link-warning">Google</a></div>
        </div>
        <div class="col-6">
            <div class="p-3 border bg-light"><a href="http://www.onet.pl" class="link-primary">Onet</a></div>
        </div>
        <div class="col-6">
            <div class="p-3 border bg-light">Custom column padding</div>
        </div>
        <div class="col-6">
            <div class="p-3 border bg-light">Custom column padding</div>
        </div>
    </div>
</div>
{% endblock %}

pywww/main/templates/main/hello.html
{% extends "main/base.html" %}
{% block title %}Lista postów{% endblock %}
{% block content %}
<h1>Nagłówek/h1>
{% endblock %}

pywww/posts/templates/posts/add.html
{% extends "main/base.html" %}
{% block title %}Dodawanie posta{% endblock %}
{% block content %}
    {{ tags }}
    <form method="POST">
        {% csrf_token %}
        <div class="sm-3">
            <label for="title" class="form-label">Post title</label>
            <input type="text" class="form-control" id="title" aria-describedby="titleHelp" name="title">
            {#            <div id="searchHelp" class="form-text">Enter post title.</div>#}

            <label for="content" class="form-label">Post content</label>
            <textarea class="form-control" id="content" aria-describedby="contentHelp" name="content"
                      rows="3"></textarea>
            {#            <div id="contentHelp" class="form-text">Enter post content.</div>#}
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="on" id="published" name="published">
                <label class="form-check-label" for="published">
                    Is post published?
                </label>
            </div>
            <label class="form-check-label" for="tags">
                Tags:
            </label>
            <select class="form-select" multiple aria-label="Tags" id="tags" name="tags">
                {% for tag in tags %}
                    <option value="{{ tag.id }}">{{ tag.name }}</option>
                {% endfor %}
                </select>
        </div>
            <label class="form-check-label" for="author">
                Autorzy:
            </label>
            <select class="form-select" aria-label="author" id="author" name="author">
                {% for author in authors %}
                    <option value="{{ author.id }}">{{ author }}</option>
                {% endfor %}
            </select>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
{% endblock %}

pywww/posts/templates/posts/details.html
{% extends "main/base.html"%}
{% block title %}Szczegóły postu{% endblock %}
{% block content %}
<div class="card" style="width: 18rem;">
  {% if post.image %}
  <img src="{{post.image.url}}" class="card-img-top" alt="Obrazek">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{post.title}}</h5>
  {% extends "main/base.html" %}
{% block title %}Szczegóły postu{% endblock %}
{% block content %}
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">by {{ post.author }}</h6>
        </div>
        <ul class="list-group list-group-flush">
            {% if post.is_content_long %}
                <li class="list-group-item">Shortened: {{ post.short_content }}...</li>
            {% else %}
                <li class="list-group-item">{{ post.content }}</li>
            {% endif %}
            <li class="list-group-item">{{ post.created }}</li>
            <li class="list-group-item">{{ post.modified }}</li>
            <li class="list-group-item">
                {% for tag in post.tags.all %}
                    <span class="badge text-bg-light" data-bs-toggle="tooltip"
                          data-bs-title="{{ tag.name }}">{{ tag.slug }}</span>
                {% endfor %}
            </li>
            {% if post.example_file %}
                <li class="list-group-item">Pobierz <a href="{{ post.example_file.url }}">przykład</a></li>
            {% endif %}
        </ul>
        <div class="card-body">
            <a href="{% url 'posts:list' %}" class="card-link">Powrót do listy postów</a>
        </div>
    </div>

{% endblock %}

pywww/posts/templates/posts/list.html
{% extends "main/base.html" %}
{% block title %}Lista postów{% endblock %}
{% block content %}
    <div class="container">
        <form>
            <div class="sm-3">
                <label for="search" class="form-label">Search posts</label>
                <input type="text" class="form-control" id="search" aria-describedby="searchHelp" name="q">
                <div id="searchHelp" class="form-text">What are you looking for?</div>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>

        {% for post in posts_list %}
            {% if post.published %}
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'posts:details' post.id %}" data-bs-toggle="tooltip"
                           data-bs-title="{{ post.id }}">
                            {% if post.sponsored %}
                                <strong>
                                    {{ post.title }}
                                </strong>
                            {% else %}
                                {{ post.title }}
                            {% endif %}
                        </a>
                    </div>
                    <div class="col text-center">
                        {{ post.created | date:"d-m-Y H:i" }}
                    </div>
                    <div class="col text-center">
                        {{ post.modified | date:"d-m-Y H:i" }}
                    </div>
                    <div class="col text-center">
                        <a href="{% url 'posts:toggle_sponsored' post.id %}">
                            {% if post.sponsored %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                </svg>
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-check-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                    <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                                </svg>                            {% endif %}
                        </a>

                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}